apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apn-preview.fullname" . }}-secrets
  labels:
    {{- include "apn-preview.labels" . | nindent 4 }}
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "root-pr-{{ .Values.pr }}-preview-pass"
  MARIADB_PASSWORD: "user-pr-{{ .Values.pr }}-preview-pass"
  WORDPRESS_DB_PASSWORD: "user-pr-{{ .Values.pr }}-preview-pass"
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.adminPassword | quote }}
