{
 "title": "Litestream Metrics",
 "tags": [
  "litestream",
  "s3"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "S3 Requests (per 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(litestream_replica_operation_total{replica_type=\"s3\"}[5m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "DB Syncs (per 5m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(litestream_sync_count[5m])) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "S3 Data Transferred (per 5m)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(litestream_replica_operation_bytes{replica_type=\"s3\"}[5m])) by (operation)",
     "legendFormat": "Bytes - {{operation}}"
    }
   ]
  },
  {
   "title": "WAL Bytes Synced (per 5m)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(litestream_total_wal_bytes[5m])) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  }
 ]
}