version: "2.1"

volumes:
  traefik-conf:

networks:
  proxy:
    external: true

services:
  traefik-configurator:
    image: alpine:latest
    container_name: traefik-configurator
    volumes:
      - traefik-conf:/conf
    command:
      - /bin/sh
      - -c
      - |
        cat << 'EOF' > /conf/dynamic.yml
        http:
          routers:
            proxmox:
              rule: "Host(`pve.kms-lab.in.ua`)"
              service: proxmox-svc
              tls: {}
            portainer:
              rule: "Host(`portainer.home.arpa`)"
              service: portainer-svc
              tls: {}
            qnap:
              rule: "Host(`nas72ffeb.home.arpa`)"
              service: qnap-svc
              tls: {}
          services:
            proxmox-svc:
              loadBalancer:
                servers:
                  - url: "https://192.168.0.26:8006"
            portainer-svc:
              loadBalancer:
                servers:
                  - url: "https://portainer:9443"
            qnap-svc:
              loadBalancer:
                servers:
                  - url: "https://host.docker.internal:4433"
        EOF
        echo "Traefik config generated successfully"

  traefik-qnap:
    depends_on:
      traefik-configurator:
        condition: service_completed_successfully
    image: traefik:v3.0
    container_name: traefik-qnap
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-conf:/etc/traefik/dynamic_conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-ui.rule=Host(`traefik.home.arpa`)"
      - "traefik.http.routers.traefik-ui.service=api@internal"
