alerting:
  ntfy:
    url: "https://ntfy.sh"
    topic: "$NTFY_TOPIC"
    priority: 4
    default-alert:
      description: "Healthcheck failed"
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

metrics: true
endpoints:
  - name: Portainer
    group: Home Infrastructure
    url: "https://portainer.home.arpa"
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: ntfy

  - name: QNAP Admin
    group: Home Infrastructure
    url: "https://nas72ffeb.home.arpa"
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: ntfy

  - name: Proxmox
    group: Home Infrastructure
    url: "https://pve.kms-lab.in.ua"
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: ntfy

  - name: Jellyfin
    group: Media
    url: "https://jellyfin.home.arpa"
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: ntfy

  - name: Radarr
    group: Media
    url: "https://radarr.home.arpa"
    interval: 1m
    client:
      insecure: true
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: ntfy
